<a href="https://colab.research.google.com/github/Snehamn24/Python_practice_questions/blob/main/Python_practice_question.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#dataypes in python


i. take a list of numbers as input and remove all duplicate values using the set and display in sorted order

In [ ]:
l=[]
n=int(input("Enter the size : "))
for i in range(n):
  l.append(int(input(f"Enter the {i+1} element : ")))
print(l)
l=list(set(l))
print(l)
#converts back  it into a list and display in sorted order
l.sort()
print(l)
l2=l.copy()
l2.sort(reverse=True)
print(l2)

Enter the size : 6
Enter the 1 element : 5
Enter the 2 element : 8
Enter the 3 element : 2
Enter the 4 element : 1
Enter the 5 element : 5
Enter the 6 element : 7
[5, 8, 2, 1, 5, 7]
[1, 2, 5, 7, 8]
[1, 2, 5, 7, 8]
[8, 7, 5, 2, 1]


create a tuple with atleast 5 values and perform slicing operations and convert to list and modify the elements and vonvert back to the tuple

In [ ]:
t1=tuple(map(int,input("Enter atleast separated by spaces 5 elements : ").split()))
print(t1)
print("Values from 2 to 4  : ",t1[2:5])
l1=list(t1)
l1[0]=100
print(l1)
t1=tuple(l1)

Enter atleast separated by spaces 5 elements : 10 20 30 40 50
(10, 20, 30, 40, 50)
Values from 2 to 4  :  (30, 40, 50)
[100, 20, 30, 40, 50]


Take a dictionary of the product
productname : quantity
1 . allow user to update the quantity of the particular product
2 . display all the product that are less than the given threshold
3 . deletes  a product from the dictionary based on the user input

In [ ]:
n=int(input("Enter the value size of the inventory : "))
products={}
for i in range(n):
  name=input("Enter the name of the product  : ")
  quantity=int(input("Enter the quantity of the products : "))
  products[name]=quantity
print(products)
update_product=input("Enter the product to change the quantitiy : ")
update_quantity=int(input("Enter the quantity to be changed : "))
products[update_product]=update_quantity
print(products)
#take a threshold
threshhold=int(input("Enter the threshold : "))
for x,y in products.items():
  if y<threshhold:
    print(x, y)
prod=input("Enter the productto be deleted : ")
del products[prod]
print(products)

Enter the value size of the inventory : 5
Enter the name of the product  : milk
Enter the quantity of the products : 5
Enter the name of the product  : almonds
Enter the quantity of the products : 6
Enter the name of the product  : butter
Enter the quantity of the products : 6
Enter the name of the product  : cheese
Enter the quantity of the products : 3
Enter the name of the product  : ragi
Enter the quantity of the products : 2
{'milk': 5, 'almonds': 6, 'butter': 6, 'cheese': 3, 'ragi': 2}
Enter the product to change the quantitiy : milk
Enter the quantity to be changed : 1
{'milk': 1, 'almonds': 6, 'butter': 6, 'cheese': 3, 'ragi': 2}
Enter the threshold : 5
milk 1
cheese 3
ragi 2
Enter the productto be deleted : milk
{'almonds': 6, 'butter': 6, 'cheese': 3, 'ragi': 2}


Take a 2 sets from the user an perform the various set operations

In [ ]:
s1=eval(input("Enter the first set elements : "))
s2=eval(input("Enter the second set elements : "))
print(s1)
print(s2)
print("union : ",s1.union(s2))
print("Intersection : ",s1.intersection(s2))
print("Difference : ",s1.difference(s2))
print("Symmetric Difference : ",s1.symmetric_difference(s2))
if s1.issubset(s2):
  print("S1 is subset ")
if s2.issubset(s2):
  print("S2 is subset")


Enter the first set elements : {1,2,3,4,5}
Enter the second set elements : {2,3,4,5}
{1, 2, 3, 4, 5}
{2, 3, 4, 5}
union :  {1, 2, 3, 4, 5}
Intersection :  {2, 3, 4, 5}
Difference :  {1}
Symmetric Difference :  {1}
S2 is subset


Classes and objects

Abstract methods

In [ ]:
from abc import *
import math
@abstractmethod
class number:
  def calculate(self,x):
    pass
class square(number):
  def calculate(self,x):
    return x*x
  def display(self):
    print("Hello World")
class cube(number):
  def calculate(self,x):
    return x*x*x
class square_root(number):
  def calculate(self,x):
    return math.sqrt(x)
obj1=square()
print(obj1.calculate(int(input("Enter a number to find the square : "))))
obj1.display()
obj2=cube()
print(obj2.calculate(int(input("Enter the number to find the cube : "))))
obj3=square_root()
print(obj3.calculate(int(input("enter the number to find the square root : "))))

Enter a number to find the square : 2
4
Hello World
Enter the number to find the cube : 3
27
enter the number to find the square root : 81
9.0


Create a interface class that connects and disconnets to the various datatypes

In [ ]:
from abc import *
class MyClass(ABC):
  @abstractmethod
  def connect(self):
    pass
  def disconnect(self):
    pass
class Sybase(MyClass):
  def connect(self):
    print("Coonnceting ot sybase database  ")
  def disconnect(self):
    print("Disconnetign from the sybase ")
class Mysql(MyClass):
  def connect(self):
    print("Connceting to the mysql ")
  def disconnect(self):
    print("Disconnecting from the mysql")
class Database:
  classname=input("enter the classname name : ")
  cn=globals()[classname]
  x=cn()
  x.connect()
  x.disconnect()

enter the classname name : Sybase
Coonnceting ot sybase database  
Disconnetign from the sybase 


Create a class called Leader. Derive this class from the
base classes Person and Employee.
The attributes of Person class are name and idnumber.
The attributes of Employee class are salary and post.

In [ ]:
class Person:
    def __init__(self, name, idnumber):
        self.name = name
        self.idnumber = idnumber


class Employee:
    def __init__(self, salary, post):
        self.salary = salary
        self.post = post


class Leader(Person, Employee):
    def __init__(self, name, idnumber, salary, post):
        Person.__init__(self, name, idnumber)
        Employee.__init__(self, salary, post)

    def display(self):
        print("Name:", self.name)
        print("ID:", self.idnumber)
        print("Salary:", self.salary)
        print("Post:", self.post)


# Object creation
l = Leader("Krishna", 101, 50000, "Manager")
l.display()

Name: Krishna
ID: 101
Salary: 50000
Post: Manager


# Numpy

In [4]:
import numpy
a=numpy.array([1,2,3])
print(a)
print(type(a))


[1 2 3]
<class 'numpy.ndarray'>


In [2]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
from numpy import *
a=array([1,2,4,5])
print(a)

[1 2 4 5]


In [2]:
#2D Array
import numpy as np
b=np.array([[1,2],[3,4]])
print(b)
print(type(b))

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


In [8]:
np.zeros(0)

array([], dtype=float64)

In [5]:

a=np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [6]:
import numpy as np
np.array([1,2,4,5])

array([1, 2, 4, 5])

In [9]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [10]:
a=np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [11]:
#creating the array uisng the arange()
import numpy as np
a=np.arange(10)
print(a)


[0 1 2 3 4 5 6 7 8 9]


In [12]:
b=np.arange(5,10)
print(b)

[5 6 7 8 9]


In [13]:
c=np.arange(1,10,3)
print(c)

[1 4 7]


In [14]:
d=np.arange(10,1,-1)
print(d)

[10  9  8  7  6  5  4  3  2]


In [15]:
e=np.arange(0,10,1.5)
print(e)

[0.  1.5 3.  4.5 6.  7.5 9. ]


In [17]:
#operations on the numpy array
a=np.array([12.4,5,7])
b=np.array([3,4,5])
print("Addtion : ",a+b)
print("Subtraction : ",a-b)
print("Multiplication : ",a*b)
print("Division : ",a/b)
print("Floor division  : ",a//b)
print(a+5)
print((b+4)**2-1)

Addtion :  [15.4  9.  12. ]
Subtraction :  [9.4 1.  2. ]
Multiplication :  [37.2 20.  35. ]
Division :  [4.13333333 1.25       1.4       ]
Floor division  :  [4. 1. 1.]
[17.4 10.  12. ]
[48 63 80]


In [21]:
a=np.array([12.4,5,7])
b=np.array([3,5,1])
c=a==b
print(c)
c=a>b
print(c)
c=a<=b
print(c)

[False  True False]
[ True False  True]
[False  True False]


In [22]:
print(type(c))


<class 'numpy.ndarray'>


In [23]:
a=np.array([1,2,3,5,6,2])
b=a.reshape(2,3)
print(b)

[[1 2 3]
 [5 6 2]]


In [25]:
a=np.array([1,2,3,5,6,2])
b=np.reshape(a,(2,3))
print(b)

[[1 2 3]
 [5 6 2]]


In [28]:
c=np.reshape(a,(3,2))
print(c)

[[1 2]
 [3 5]
 [6 2]]


In [34]:
a=np.arange(12)
print(a)
b=a.reshape(2,3,2)
print(b)
print("=========================")
b=a.reshape(3,2,2)
print(b)
print(b.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
3


In [35]:
import numpy as np

a = np.arange(8)
print(a)

b = a.reshape(2,4)
print(b)

[0 1 2 3 4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]


In [36]:
import numpy as np

a = np.arange(12)
b = a.reshape(2,2,3)

print(b)
print(b.ndim)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
3


In [37]:
import numpy as np

a = np.arange(16)
b = a.reshape(2,2,4)

print(b)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


In [44]:
import numpy as np

a = np.arange(24)

b = a.reshape(2,3,4)
print(b)

c = a.reshape(4,3,2)
print(c)

print(b.ndim)
print(len(b))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
3
2


In [42]:
d=np.array([1,2,3])
print(len(d))

3


In [43]:
print(d.ndim)

1


In [46]:
import numpy as np

a = np.arange(24)

b = a.reshape(2,3,4)
print(b)
print(len(b))
print(b.ndim)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
2
3


In [52]:
a=np.array([[1,2,4,5],[3,7,8,4]],ndmin=4)
print(a)
print(a.shape)
print(a.reshape(2,2,2))

[[[[1 2 4 5]
   [3 7 8 4]]]]
(1, 1, 2, 4)
[[[1 2]
  [4 5]]

 [[3 7]
  [8 4]]]


In [51]:
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print(arr.shape)

[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)


In [55]:
a=np.array([[[1,2,3],
             [5,6,2]],
            [[9,5,3],
             [10,34,12]]])
print(a)
print(a.shape)

[[[ 1  2  3]
  [ 5  6  2]]

 [[ 9  5  3]
  [10 34 12]]]
(2, 2, 3)


In [56]:
print(a.ndim)

3


In [57]:
print(a.itemsize)
print(a.size)
print(a.dtype)
print(a.nbytes)


8
12
int64
96


In [58]:
a=np.array([[[1.0,2,3],
             [5,6,2]],
            [[9,5,3],
             [10,34,12]]])
print(a)
print(a.shape)

[[[ 1.  2.  3.]
  [ 5.  6.  2.]]

 [[ 9.  5.  3.]
  [10. 34. 12.]]]
(2, 2, 3)


In [59]:
print(a.itemsize)
print(a.size)
print(a.dtype)
print(a.nbytes)


8
12
float64
96


In [60]:
a=np.array([[["sneha",2,3],
             [5,6,2]],
            [[9,5,3],
             [10,34,12]]])
print(a)
print(a.shape)

[[['sneha' '2' '3']
  ['5' '6' '2']]

 [['9' '5' '3']
  ['10' '34' '12']]]
(2, 2, 3)


In [61]:
print(a.itemsize)
print(a.size)
print(a.dtype)
print(a.nbytes)

84
12
<U21
1008


In [64]:
names=np.array(["rahul","Akshaya"])
print(names.ndim)

1


In [65]:
print(names.itemsize)
print(names.size)
print(names.dtype)
print(names.nbytes)

28
2
<U7
56


In [68]:
a=np.array([[["sneha",2,3],
             [5,6,2]],
            [[9,5,3],
             [10,34,12]]])
print(a)
print(a.shape)
print(a.itemsize)
print(a.size)
print(a.dtype)
print(a.nbytes)


[[['sneha' '2' '3']
  ['5' '6' '2']]

 [['9' '5' '3']
  ['10' '34' '12']]]
(2, 2, 3)
84
12
<U21
1008


In [69]:
a=np.array([[["snehamn",2,3],
             [5,6,2]],
            [[9,5,3],
             [10,34,12]]])
print(a)
print(a.shape)
print(a.itemsize)
print(a.size)
print(a.dtype)
print(a.nbytes)


[[['snehamn' '2' '3']
  ['5' '6' '2']]

 [['9' '5' '3']
  ['10' '34' '12']]]
(2, 2, 3)
84
12
<U21
1008


In [79]:
import numpy as np

# Using standard operators (vectorized)
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result_add = arr1 + arr2
print(result_add)
# Output: [5 7 9]

# Using the explicit ufunc
result_sqrt = np.sqrt(arr1)
print(result_sqrt)
# Output: [1. 1.41421356 1.73205081]

# Using a comparison ufunc
result_comparison = np.greater(arr2, arr1)
print(result_comparison)
# Output: [True True True]

print(np.add(arr1,arr2))


[5 7 9]
[1.         1.41421356 1.73205081]
[ True  True  True]
[5 7 9]


In [77]:
nums=np.array([-2,-3])
print(np.abs(nums))

[2 3]


In [76]:
arr1=np.array([3,4,5])
arr2=np.array([9,5,6])
print(np.maximum(arr1,arr2))
print(np.minimum(arr1,arr2))


[9 5 6]
[3 4 5]


In [80]:
nums=np.array([2,3])
print(np.negative(nums))

[-2 -3]


In [85]:
#aggreagate functions
data=np.array([[1,2,3],[4,5,6]])
mean=np.mean(data)
print(mean)
mean_col=np.mean(data,axis=0)
print(mean_col)
mean_row=np.mean(data,axis=1)
print(mean_row)

3.5
[2.5 3.5 4.5]
[2. 5.]


In [88]:
#aggreagate functions
data=np.array([[1,2,3],[4,5,6]])
median=np.median(data)
print(median)
median_col=np.median(data,axis=0)
print(median_col)
median_row=np.median(data,axis=1)
print(median_row)

3.5
[2.5 3.5 4.5]
[2. 5.]


In [89]:
a=np.array([[10,20,30],[40,50,60]])
b=np.array([[10],[20]])
print(a+b)

[[20 30 40]
 [60 70 80]]


In [90]:
a=np.array([0,10,20,30])
b=np.array([1,2,3])
print(a+b)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [92]:
a=np.array([1,2,3,4,5])
b=np.array([5,4,3,2,1])
print(a==b)
print(a[a<3])

[False False  True False False]
[1 2]


In [93]:
x=np.arange(16).reshape((4,4))
row=np.array([0,1,2])
col=np.array([3,1,2])
print(x[row,col])

[ 3  5 10]
